Repository WildCodeSchool/lyon-js-sept2020-p3-oufgarden-api, pull requests merged in 2020-12, with the labels that each got.

#7 Loginbackoffice
  controllers/loginBO.js
  controllers/users.js
  models/loginBO.js
  models/users.js
  routes/index.js
  routes/loginBO.js
  routes/users.js
Labels: Ready for validation

#8 Article to tags
  controllers/articles.js
  controllers/tags.js
  models/articles.js
  models/tags.js
  routes/index.js
  routes/tags.js
Labels: WIP

#3 Articles routes
  .env.sample
  controllers/articles.js
  controllers/tagToArticle.js
  controllers/tags.js
  migrations/20201210133325-changeArticleContentDataType.js
  migrations/sqls/20201210133325-changeArticleContentDataType-down.sql
  migrations/sqls/20201210133325-changeArticleContentDataType-up.sql
  models/articles.js
  models/tagToArticle.js
  models/tags.js
  routes/articles.js
  routes/index.js
  routes/tagToArticle.js
  routes/tags.js
Labels: Fixed - ready for prod

#12 merged with dev
  middlewares/handleValidationError.js
Labels: Ready for prod
