Repository WildCodeSchool/lyon-js-sept2020-p3-oufgarden-api, pull requests merged in 2021-01, with the labels that each got.

#14 Garden table
  controllers/garden.js
  controllers/login.js
  controllers/plantFamily.js
  migrations/20201217090110-gardenModification.js
  migrations/20201217162231-newModifGarden.js
  migrations/20210104141534-updateTablesGarden.js
  migrations/20210105103337-addColumnsToZoneTabme.js
  migrations/sqls/20201217090110-gardenModification-down.sql
  migrations/sqls/20201217090110-gardenModification-up.sql
  migrations/sqls/20201217162231-newModifGarden-down.sql
  migrations/sqls/20201217162231-newModifGarden-up.sql
  migrations/sqls/20210104141534-updateTablesGarden-down.sql
  migrations/sqls/20210104141534-updateTablesGarden-up.sql
  migrations/sqls/20210105103337-addColumnsToZoneTabme-down.sql
  migrations/sqls/20210105103337-addColumnsToZoneTabme-up.sql
  models/garden.js
  models/login.js
  models/plantFamily.js
  routes/garden.js
  routes/index.js
  routes/login.js
  routes/plantFamily.js
Labels: Fixed - ready for prod

#18 created a new migration to create the articleToGarden table, and to a…
  migrations/20210106170809-createArticleToGardenTable.js
  migrations/sqls/20210106170809-createArticleToGardenTable-down.sql
  migrations/sqls/20210106170809-createArticleToGardenTable-up.sql
Labels: Ready for validation

#21 Update article
  controllers/articles.js
  models/articles.js
Labels: Ready for validation

#16 Improving garden data validation
  controllers/users.js
  migrations/20210107140230-updateUserTable.js
  migrations/sqls/20210107140230-updateUserTable-down.sql
  migrations/sqls/20210107140230-updateUserTable-up.sql
  models/garden.js
  models/users.js
  routes/tagToArticle.js
Labels: Ready for prod

#27 Routes comments
  controllers/comments.js
  middlewares/extractCurrentUser.js
  middlewares/requireAdmin.js
  migrations/20210118172420-updateCommentTable.js
  migrations/sqls/20210118172420-updateCommentTable-down.sql
  migrations/sqls/20210118172420-updateCommentTable-up.sql
  models/comments.js
  routes/comments.js
  routes/index.js
Labels: Ready for validation

#23 Email user creation
  controllers/users.js
  mailConfig.js
  models/garden.js
  package-lock.json
  package.json
Labels: Ready for validation

#29 Routes favorites
  controllers/articles.js
  models/articles.js
  routes/articles.js
Labels: Ready for validation
